### ISSUE TITLE
Wrong path when extracting release archives

### ISSUE THREAD

**Issue by gabrielivascu** [kaniini/libucontext#12]
All `zip` and `tar.gz` releases extract to a path prefixed with the string `"libucontext-"`, which is unnecessary and can even cause issues when used in automatic scripts or makefiles.

Example:
* Expected output: `libucontext-0.1.3.tar.gz` extracts to `libucontext-0.1.3/`
* Actual output: `libucontext-0.1.3.tar.gz` extracts to `libucontext-libucontext-0.1.3/`

Same for `zip` archives and other versions.

**Comment by kaniini** [comment]
real libucontext releases are at https://distfiles.dereferenced.org/libucontext/
