### ISSUE TITLE
Two 1.2 versions and duplicate directory name?

### ISSUE THREAD

**Issue by firasuke** [kaniini/libucontext#42]
Upon checking the tags page I saw `v1.2` and `libucontext-1.2`, any difference between the two?

**Comment by firasuke** [comment]
Another thing is the directory name after extracting the tarball is `libucontext-libucontext-1.2` instead of `libucontext-1.2`.

**Comment by nekopsykose** [comment]
that's just a github thing where the tarball name and contents are `$projectname-$tag`, so if the tag is `libucontext-1.2` it looks doubled

**Comment by kaniini** [comment]
Use https://distfiles.dereferenced.org/libucontext/ for official tarballs.  GitHub screws them up.

**Comment by firasuke** [comment]
I see, thanks!

**Comment by firasuke** [comment]
Would it be possible to provide gzipped tarballs on  https://distfiles.dereferenced.org/libucontext/ as well?

**Comment by nekopsykose** [comment]
who can't decompress xz in 2023

**Comment by firasuke** [comment]
> who can't decompress xz in 2023

I don't think it's a matter of who can decompress and who can't.

I was previously using the GitHub releases page for the project, which provides gzipped tarballs, and I prefer gzip to xz for decompression speed on old or low-end machines, and I was asking if it were possible for you to provide gzipped tarballs as well.

**Comment by nekopsykose** [comment]
normally i would agree, but even on 25 year old hardware a 25k .tar.xz decompression is practically instant. are you asking because there is some case where it takes 30 seconds, or is this just some weirdly hypothetical request?

**Comment by firasuke** [comment]
In a sense it is a request, but I guess it is up to you. Is there even a difference between the gzipped source tarballs that GitHub provides, and the official xzipped tarballs other than the name inconvenience?

**Comment by nekopsykose** [comment]
note that i'm not a developer here :)  

> Is there even a difference between the gzipped source tarballs that GitHub provides, and the official xzipped tarballs other than the name inconvenience?  

there's no git-generated version difference stuff or autoconf to worry about, so it seems the same to me if you use meson, at least
