### ISSUE TITLE
Downloaded libucontext-1.3.1.tar.gz extracts into directory `./libucontext-libucontext-1.3.1/`

### ISSUE THREAD

**Issue by VolkerChristian** [kaniini/libucontext#62]
I am just working on upgrading libucontext in openwrt to the latest version 1.3.1. For that i have just downloaded the libucontext-1.3.1.tar.gz from the releases page [https://github.com/kaniini/libucontext/archive/refs/tags/libucontext-1.3.1.tar.gz](https://github.com/kaniini/libucontext/archive/refs/tags/libucontext-1.3.1.tar.gz) and extracted it.
I have expected, that the tar.gz extracts into a/the directory `./libucontext-1.3.1/` as it should but in fact it extracts into the directory `./libucontext-libucontext-1.3.1/`.
This makes it hard to upgrade the package. A release tagged with `v1.3.1` would be helpful like the release tagged with `v1.2`. Is it possible to fix this issue?

Beste regards
Volker

**Comment by kaniini** [comment]
I do not use Github to distribute releases.  Look at distfiles.ariadne.space/libucontext.
