### ISSUE TITLE
Meson build system issue for the `loongarch64` and `x86` architectures

### ISSUE THREAD

**Issue by VolkerChristian** [kaniini/libucontext#64]
The build system is currently broken for loongarch64 and x86. They need to use `startcontext.S` instead of `trampoline.c`. Fixed in pull request #63.

**Comment by barracuda156** [comment]
@VolkerChristian Just in case, do you happen to know what is needed to fix this? https://github.com/kaniini/libucontext/issues/65
Besides the obvious: use ABI-compatible syntax. I am somewhat confused by a number of registers the source uses there.

**Comment by kaniini** [comment]
@VolkerChristian i'll roll a 1.3.2 release with this this weekend!
