### ISSUE TITLE
Error in riscv64/swapcontext.S

### ISSUE THREAD

**Issue by mobsense** [kaniini/libucontext#67]
Should the code:

```
	/* return register block */
	sd x0, REG_OFFSET(REG_A0)(a0)
	sd x0, REG_OFFSET(REG_A1)(a0)
```

not be:

	/* return register block */
	sd x0, REG_OFFSET(REG_A0)(a0)
	sd x1, REG_OFFSET(REG_A1)(a0)

.ie.

Should the second x0 be x1?

**Comment by mobsense** [comment]
Same in riscv/swapcontext.S

**Comment by kaniini** [comment]
No.  We want the return registers to be saved as zero.  x0 is always zero.

**Comment by mobsense** [comment]
Thanks for the quick turn around.
