### ISSUE TITLE
argument passing seems to be broken

### ISSUE THREAD

**Issue by george-hopkins** [kaniini/libucontext#9]
It seems that the second argument, which is passed to the function after a context switch, gets modified. To  test this I [modified `test_libucontext.c`](https://gist.github.com/george-hopkins/33f7783aa0c9ab5943348eacdefe530b) slightly. I would expect the output to be:
```text
start f2
start f1: 1 2 3 4
finish f2
finish f1
```
However, I actually get `start f1: 1 X 3 4` where X is 66 (might be an arbitrary number) on Alpine Linux edge x64.

**Comment by fabled** [comment]
Is this affecting other arch than x86_64 or just one arch?
